
spring:
  datasource:
    url: jdbc:mysql://35.220.247.103:3306/yg_api
    username: toor
    password: 123456test
    driverClassName:  com.mysql.jdbc.Driver
logging:
  level:
    com.admin.out.api.newadminoutapi: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9991
